# ชื่อของ Workflow ที่จะแสดงในหน้า Actions ของ GitHub
name: Run Daily Forex Analysis

# ตั้งค่าการเรียกใช้งาน (Trigger)
on:
  workflow_dispatch: # อนุญาตให้เรากดรันเองได้เพื่อทดสอบ
  schedule:
    - cron: '30 23 * * 0-4'

# กำหนดงานที่จะต้องทำ
jobs:
  build-and-run:
    # เลือกระบบปฏิบัติการที่จะใช้รัน
    runs-on: ubuntu-latest

    # ขั้นตอนการทำงานทั้งหมด
    steps:
      # 1. เช็คเอาท์โค้ดของเราจาก Repository
      - name: Check out repository code
        uses: actions/checkout@v4

      # 2. ตั้งค่าสภาพแวดล้อม Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9' # เลือกรุ่น Python ที่เสถียร

      # 3. ติดตั้ง Dependencies ของ Playwright (สำคัญมาก!)
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # 4. ติดตั้ง Python Dependencies ทั้งหมด
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -U git+https://github.com/iqoptionapi/iqoptionapi.git@7.1.1

      # 5. รันสคริปต์หลักของเรา!
      - name: Run Forex Analysis Script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          TYPHOON_API_KEY: ${{ secrets.TYPHOON_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          SIGNAL_BOT_TOKEN: ${{ secrets.SIGNAL_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          IQ_USER: ${{ secrets.IQ_USER }}
          IQ_PASS: ${{ secrets.IQ_PASS }}
        run: python forex_daily_news.py